leftnav:
- identifier: 0de1dfb4-9e6d-8033-b423-c25953caf7fe
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 29c0f94f-96c7-e032-7b5e-d87bec6628ca
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 2e69d22a-85af-a7f9-9f4c-248772376fc8
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 1598d072-9397-c34c-77f7-867b964e9975
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 429e2112-09a7-0694-ae1a-02c36988a3ca
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
- identifier: 849d014e-0b12-9c05-c621-f344ad50ad63
  name: Exams
  pageRef: /pages/exams
  weight: 60
- identifier: 8acaf564-fabb-3e34-7818-9113907b5e28
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 70
